- name: Test my user_info module
  hosts: all
  gather_facts: true
  gather_subset:
    - '!all'
    - 'os_family'
  vars:
    debian: 'vscode'
    redhat: 'devuser'
  tasks:
    - name: Dump gathered facts
      ansible.builtin.debug:
        msg: '{{ ansible_facts["os_family"] }}'
    - name: Run the User module Debian
      when: ansible_facts['os_family'] == 'Debian'
      block:
        - name: Run the User module (Debian)
          user_info:
            username: '{{ debian }}'
          register: user_info_output
        - name: Dump test output
          ansible.builtin.debug:
            msg: '{{ user_info_output }}'
    - name: Run the User module Debian
      when: ansible_facts['os_family'] == 'RedHat'
      block:
        - name: Run the User module (RedHat)
          user_info:
            username: '{{ redhat }}'
          register: user_info_output
        - name: Dump test output
          ansible.builtin.debug:
            msg: '{{ user_info_output }}'


