- name: Test my user_info module
  hosts: all
  gather_facts: false
  vars:
    debian: 'vscode'
    redhat: 'devuser'
  tasks:
    - name: Dump Setup user
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - 'os_family'
          - 'user'
      register: setup_output
    - name: Dump Limited Setup output
      ansible.builtin.debug:
        msg: '{{ setup_output }}'
    - name: Dump login user from Setup output
      ansible.builtin.debug:
        msg: '{{ setup_output.ansible_facts.ansible_user_id }}'
    - name: Dump login user using the ansible_fact dictionary
      ansible.builtin.debug:
        msg: '{{ ansible_facts["user_id"] }}'
    - name: Dump gathered facts
      ansible.builtin.debug:
        msg: '{{ ansible_facts["os_family"] }}'
    - name: Run the User module Debian
      when: ansible_facts['os_family'] == 'Debian'
      block:
        - name: Run the User module (Debian)
          user_info:
            username: '{{ debian }}'
          register: user_info_output
        - name: Dump test output
          ansible.builtin.debug:
            msg: '{{ user_info_output }}'
    - name: Run the User module Debian
      when: ansible_facts['os_family'] == 'RedHat'
      block:
        - name: Run the User module (RedHat)
          user_info:
            username: '{{ redhat }}'
          register: user_info_output
        - name: Dump test output
          ansible.builtin.debug:
            msg: '{{ user_info_output }}'


