---
- name: Terraform
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    terraform_state: "present"
  tasks:
    - name: Apply or destroy resources with terraform
      community.general.terraform:
        project_path: "{{ playbook_dir }}/terraform"
        state: "{{ terraform_state }}"
        force_init: true
      register: terraform_result
    - name: Debug terraform result
      ansible.builtin.debug:
        msg: "{{ terraform_result }}"

    - name: Validate the terraform output if state is present
      ansible.builtin.debug:
        msg:
          - "Status:{{ terraform_result.outputs.installation_status.value }}"
          - "State:{{ terraform_result.state }}"
      when: terraform_state == 'present' and terraform_result is defined

    - name: Check if terraform apply/destroy was successful
      ansible.builtin.assert:
        that:
          - terraform_result is defined
          - terraform_result.changed == true
          - terraform_result.failed == false
        fail_msg: "Terraform apply/destroy failed"
        success_msg: "Terraform apply/destroy succeeded"
      failed_when: terraform_result.failed == true
