---
- name: Gather service Facts
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Display service state (sudo) when running
      ansible.builtin.debug:
        msg: "Sudo is running on {{ ansible_facts['hostname'] }}"
      when: ansible_facts.services.sudo.state == 'running'
    - name: Display service state (sudo) when stopped
      ansible.builtin.debug:
        msg: "Sudo is stopped on {{ ansible_facts['hostname'] }}"
      when: ansible_facts.services.sudo.state != 'running'
